//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IDcalificacion { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Calificacion1 { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
