//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.DetallesOrdens = new HashSet<DetallesOrden>();
        }
    
        public int IDOrden { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<int> IDDireccion { get; set; }
        public Nullable<int> IDTarjeta { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IDVendedor { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesOrden> DetallesOrdens { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Orden Orden1 { get; set; }
        public virtual Orden Orden2 { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
