//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int IDTarjeta { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Expiracion { get; set; }
        public string CVV { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
